# я думаю тут понятно, где что

[colors]
background=1e1e2eff
text=cdd6f4ff
prompt=89b4faff
placeholder=101010ff
input=cdd6f4ff
match=f38ba8ff
selection=1b1b2bff
selection-text=74c7ecff
selection-match=f38ba8ff
counter=8087a2ff
border=89b4faff

[border]
width = 3
radius = 10
selection-radius = 10

[main]
tabs = 8
lines = 10
width = 30
prompt = " "
layer = overlay
line-height = 25
sort-result = false
font = JetBrainsMono NFP:size=12
icon-theme = fairywren
enable-mouse = false
terminal = kitty
