hl.curve("shot", {type = "bezier", points = { {0.2, 1}, {0.2, 1} }})
hl.curve("swipe", {type = "bezier", points = { {0.6, 0}, {0.2, 1.05} }})
hl.curve("linear", {type = "bezier", points = { {0, 0}, {1, 1} }})
hl.curve("progressive", {type = "bezier", points = { {1, 0}, {0.6, 1} }})

hl.animation({ leaf = "border",        enabled = true,  speed = 6, bezier = "linear" })
hl.animation({ leaf = "windows",       enabled = true,  speed = 6, bezier = "shot", style = "slide"})
hl.animation({ leaf = "fade",          enabled = true,  speed = 4, bezier = "progressive" })
hl.animation({ leaf = "workspaces",    enabled = true,  speed = 6, bezier = "swipe", style = "slide" })
hl.animation({ leaf = "borderangle",    enabled = true,  speed = 100, bezier = "linear", style = "loop" })