general {
    # отступы
    gaps_in = 2
    gaps_out = 5

    # границы окон
    border_size = 0

    col.active_border = rgba(89b4faaa)
    col.inactive_border = rgba(1e1e1eaa)

    resize_on_border = false

    allow_tearing = false

    # dwintle, master, scrolling
    layout = scrolling
}

# декорации окна
decoration {
    rounding = 15
    rounding_power = 2

    active_opacity = 1
    inactive_opacity = 1	

    shadow {
        enabled = false
        range = 4
        render_power = 3
        color = rgba(1a1a1aee)
    }

    blur {
        enabled = true
        size = 2
        passes = 1

        vibrancy = 0.125
    }
}
