# проги

$nvtop = kitty nvtop
$htop = kitty htop
$terminal = alacritty
$fileManager = kitty ranger
$menu = fuzzel
$browser = chromium
$launcher = prismlauncher

# некоторые функции

$screenshot = bash /home/$USER/.config/fuzzel/screenshot.sh
$quick_screenshot = hyprshot -m region -z -o ~/Pictures/Screenshots/
$pick = hyprpicker -a
$wipe = cliphist wipe

$clipboard = cliphist list | fuzzel --dmenu | cliphist decode | wl-copy