# проги

$nvtop = kitty nvtop
$htop = kitty htop
$terminal = alacritty
$fileManager = kitty ranger
$menu = fuzzel

# некоторые функции

# !!!ПОМЕНЯТЬ power-button НА НАЗВАНИЕ ВАШЕЙ КЛАВИАТУРЫ В hyprctl devices!!!
$rskb = hyprctl switchxkblayout power-button 0